import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@components/Button'
import { useEffect, useRef, useState } from 'react'

const Home: NextPage = () => {
  const [products, setProducts] = useState<
    { id: string; properties: { id: string }[] }[]
  >([])
  useEffect(() => {
    fetch('/api/get-items')
      .then((res) => res.json())
      .then((data) => setProducts(data.items))
  }, [])
  const inputRef = useRef<HTMLInputElement>(null)

  const handleClick = () => {
    if (inputRef.current === null || inputRef.current.value === '') {
      alert('name을 넣어주세요')
      return
    }

    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <input ref={inputRef} type="text" placeholder="name" />
          <button onClick={handleClick}>Add Jacket</button>
        </div>
        <div>
          <p>Product List</p>
          {products &&
            products.map((product, index) => (
              <>
                <div className="items" key={product.id}>
                  {JSON.stringify(product)}
                  <br />
                </div>
                <div>
                  {product.properties &&
                    Object.entries(product.properties).map(([key, value]) => (
                      <button
                        key={value.id}
                        onClick={() => {
                          fetch(
                            `/api/get-detail?pageId=${product.id}&propertiesId=${value.id}`
                          )
                            .then((res) => res.json())
                            .then((data) => alert(JSON.stringify(data.detail)))
                        }}
                      >
                        {key}
                      </button>
                    ))}
                </div>
              </>
            ))}
        </div>
        <style jsx>{`
          .container {
            margin: 50px;
          }
          .items {
            color: #ffffff;
          }
        `}</style>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
